/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class tw_com_dmatek_dma210xp_uart_Linuxc */

#include <jni.h>
#ifndef _Included_com_jpjy_basket_Linuxc
#define _Included_com_jpjy_basket_Linuxc
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_com_jpjy_basket_Linuxc_openUart
  (JNIEnv *, jobject, jstring);


JNIEXPORT void JNICALL Java_com_jpjy_basket_Linuxc_closeUart
  (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_jpjy_basket_Linuxc_setUart
  (JNIEnv *, jobject,jint);


JNIEXPORT jint JNICALL Java_com_jpjy_basket_Linuxc_sendMsgUart
  (JNIEnv *, jobject, jstring);


JNIEXPORT jstring JNICALL Java_com_jpjy_basket_Linuxc_receiveMsgUart
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif

